# Generated by Django 4.0.4 on 2022-05-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Manutenção'), ('e', 'Em emprestimo'), ('d', 'Disponivel'), ('i', 'Indisponivel'), ('r', 'Reservado')], default='m', help_text='Disponibilidade do livro', max_length=1),
        ),
    ]
